{{- if hasKey .Values.spring.config "content" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: "{{ .Release.Name | trimSuffix "-canary" | trimSuffix "-stable" }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    code-app: "{{ .Values.codeapp }}"
    tier: "{{ .Values.tier }}"
    component: "JAVA"
    function: "{{ .Values.function }}"
    {{- if or (hasSuffix "-stable" .Release.Name) (hasSuffix "-canary" .Release.Name) }}
    version: "{{ .Release.Name | trunc -6 }}"
    {{- end }}
data:
  external-config.yml: |
{{ toYaml .Values.spring.config.content | indent 4  }}
{{- end }}