apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Values.version }}"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: "{{ .Release.Name }}"
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    codeAP: "{{ .Values.codeAP }}"
    tier: "{{ .Values.tier }}"
    component: "JAVA"
    function: "{{ .Values.function }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"
        chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
        codeAP: "{{ .Values.codeAP }}"
        tier: "{{ .Values.tier }}"
        component: "JAVA"
        function: "{{ .Values.function }}"
        version: "{{ .Values.version }}"
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
    spec:
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      containers:
        - name: "{{ .Release.Name }}-{{ .Values.version }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
            - name: JAVA_OPTS
              value: {{ .Values.javaopts | quote }}
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if .Values.secretRef.enabled }}
          envFrom:
            - secretRef:
                name: "{{ .Release.Name }}-secret"
          {{- end }}
          volumeMounts:
            {{- if .Values.pvc.enabled }}
            - name: {{ .Release.Name }}
              mountPath: "/applis/shared"
            {{- end -}}
            {{- if hasKey .Values.spring.config "contents" }}
            - name: config
              mountPath: /applis/config
            {{- end -}}
            {{ if .Values.spring.config.clientCerts.enabled }}
            - name: "{{ .Release.Name }}-security"
              mountPath: /applis/security
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- if .Values.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.pvc.enabled }}
        - name: {{ .Release.Name }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}
      {{- end }}
      {{- if hasKey .Values.spring.config "contents" }}
        - name: config
          configMap:
            name: "config-{{ .Values.version }}"
      {{- end }}
      {{- if .Values.spring.config.clientCerts.enabled }}
        - name: "{{ .Release.Name }}-security"
          secret:
            secretName: "{{ .Release.Name }}-security"
      {{- end }}