{{ if .Values.hpa.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: "{{ .Release.Name | trimSuffix "-canary" | trimSuffix "-stable" }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    code-app: "{{ .Values.codeapp }}"
    tier: "{{ .Values.tier }}"
    component: "JAVA"
    function: "{{ .Values.function }}"
    {{- if or (hasSuffix "-stable" .Release.Name) (hasSuffix "-canary" .Release.Name) }}
    version: "{{ .Release.Name | trunc -6 }}"
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{ .Release.Name }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.hpa.metrics.cpu.targetAverageUtilization }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ .Values.hpa.metrics.memory.targetAverageUtilization }}
{{ end }}