{{- if and .Values.ingress.enabled (not (hasSuffix "-canary" .Release.Name)) -}}
{{- $httpPort := .Values.service.httpPort }}
{{- $name := .Release.Name | trimSuffix "-canary" | trimSuffix "-stable" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    app: "{{ .Release.Name | trimSuffix "-canary" | trimSuffix "-stable" }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    code-app: "{{ .Values.codeapp }}"
    tier: "{{ .Values.tier }}"
    component: "JAVA"
    function: "{{ .Values.function }}"
  name: "{{ .Release.Name | trimSuffix "-canary" | trimSuffix "-stable" }}"
  namespace: {{ .Release.Namespace | quote }}
spec:
  rules:
  {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        {{- if index $.Values.ingress "annotations" }}
          {{- if eq (index $.Values.ingress.annotations "kubernetes.io/ingress.class" | default "") "gce" "alb" }}
          - path: /*
          {{- else }}{{/* Has annotations but ingress class is not "gce" nor "alb" */}}
          - path: /
          {{- end }}
        {{- else}}{{/* Has no annotations */}}
          - path: /
        {{- end }}
            backend:
              serviceName: {{ $name }}
              servicePort: {{ $httpPort }}
  {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
    - secretName: {{ .Values.ingress.tls.secretName }}
      hosts:
        - {{ .Values.ingress.host }}
  {{- end -}}
{{- end -}}