{{ if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: "{{ .Release.Name | trimAll "-canary" | trimAll "-stable" }}"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: "{{ .Release.Name | trimAll "-canary" | trimAll "-stable" }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    code-app: "{{ .Values.codeapp }}"
    tier: "{{ .Values.tier }}"
    component: "JAVA"
    function: "{{ .Values.function }}"
spec:
  host: "{{ .Release.Name | trimAll "-canary" | trimAll "-stable" }}"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: "{{ .Release.Name | trimAll "-canary" | trimAll "-stable" }}"
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Release.Name | trimAll "-canary" | trimAll "-stable" }}"
spec:
  hosts:
  - "*"
  gateways:
  - "{{ .Release.Name | trimAll "-canary" | trimAll "-stable" }}"
    route:
    - destination:
        host: "{{ .Release.Name | trimAll "-canary" | trimAll "-stable" }}"
        port:
          number: 8080
{{ end }}