{{ if .Values.istio.enabled }}
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Release.Name }}
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    codeAP: {{ .Values.codeAP }}
    tier: {{ .Values.tier }}
    component: JAVA
    function: {{ .Values.function }}  
spec:
  destination:
    name: "{{ .Release.Name }}"
  precedence: 1
  route:
  - labels:
      version: "current"
    weight: {{ .Values.istio.current.weight }}
{{ if .Values.base.enabled }}
  - labels:
      version: "canary"
    weight: {{ .Values.istio.cannary.weight }}
{{ end }}
{{ end }}