{{ if and .Values.istio.enabled (not (hasSuffix "-canary" .Release.Name)) }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: "{{ .Release.Name | trimSuffix "-canary" | trimSuffix "-stable" }}"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: "{{ .Release.Name | trimSuffix "-canary" | trimSuffix "-stable" }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    code-app: "{{ .Values.codeapp }}"
    tier: "{{ .Values.tier }}"
    component: "JAVA"
    function: "{{ .Values.function }}"
spec:
  host: "{{ .Release.Name | trimSuffix "-canary" | trimSuffix "-stable" }}"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary
{{ end }}