{{- if and .Values.pvc.enabled (not (hasSuffix "-canary" .Release.Name)) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Release.Name | trimAll "-canary" | trimAll "-stable" }}"
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    ibm.io/auto-create-bucket: "true"
    ibm.io/auto-delete-bucket: "false"
    ibm.io/bucket: "{{ .Release.Name }}"
    ibm.io/secret-name: "cos-write-access"
  labels:
    app: "{{ .Release.Name | trimAll "-canary" | trimAll "-stable" }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    code-app: "{{ .Values.codeapp }}"
    tier: "{{ .Values.tier }}"
    component: "JAVA"
    function: "{{ .Values.function }}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi # Enter a fictitious value
  storageClassName: {{ .Values.pvc.storageClassName }}
{{- end }}