{{- if and .Values.pvc.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    ibm.io/auto-create-bucket: "true"
    ibm.io/auto-delete-bucket: "false"
    ibm.io/bucket: "{{ .Release.Name }}"
    ibm.io/secret-name: "cos-write-access"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi # Enter a fictitious value
  storageClassName: {{ .Values.pvc.storageClassName }}
{{- end }}