{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: "{{ .Release.Name }}"
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    codeAP: "{{ .Values.codeAP }}"
    tier: "{{ .Values.tier }}"
    component: "JAVA"
    function: "{{ .Values.function }}"
spec:
  selector:
    matchLabels:
        app: "{{ .Release.Name }}"
        chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
        codeAP: "{{ .Values.codeAP }}"
        tier: "{{ .Values.tier }}"
        component: "JAVA"
        function: "{{ .Values.function }}"
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{- end }}