{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ .Release.Name }}"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: "{{ .Release.Name | trimAll "-canary" | trimAll "-stable" }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    code-app: "{{ .Values.codeapp }}"
    tier: "{{ .Values.tier }}"
    component: "JAVA"
    function: "{{ .Values.function }}"
    {{- if or (hasSuffix "-stable" .Release.Name) (hasSuffix "-canary" .Release.Name) }}
    version: "{{ .Release.Name | trunc -6 }}"
    {{- end }}
spec:
  selector:
    matchLabels:
        app: "{{ .Release.Name | trimAll "-canary" | trimAll "-stable" }}"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
        code-app: "{{ .Values.codeapp }}"
        tier: "{{ .Values.tier }}"
        component: "JAVA"
        function: "{{ .Values.function }}"
        {{- if or (hasSuffix "-stable" .Release.Name) (hasSuffix "-canary" .Release.Name) }}
        version: "{{ .Release.Name | trunc -6 }}"
        {{- end }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{- end }}