{{- if and (.Values.service.enabled) (not (hasSuffix "-canary" .Release.Name)) -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name | trimSuffix "-canary" | trimSuffix "-stable" }}"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: "{{ .Release.Name | trimSuffix "-canary" | trimSuffix "-stable" }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    code-app: "{{ .Values.codeapp }}"
    tier: "{{ .Values.tier }}"
    component: "JAVA"
    function: "{{ .Values.function }}"
spec:
  type: {{ .Values.service.type }}
  {{- if (eq .Values.service.type "LoadBalancer") }}
  {{- if hasKey .Values.service "externalTrafficPolicy" -}}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ default "" .Values.service.loadBalancerIP | quote }}
  {{- end }}
  ports:
  - name: http
    port: {{ .Values.service.httpPort }}
    protocol: TCP
    targetPort: {{ .Values.containerPort }}
  selector:
    app: "{{ .Release.Name | trimSuffix "-canary" | trimSuffix "-stable" }}"
{{- end -}}